<?php
/**
 * @file
 * unhcr.module
 */

function unhcr_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['menu_item'] = array(
    'label' => t('Menu item'),
    'custom settings' => TRUE
  );
}

function unhcr_preprocess_node(&$vars) {
  if ($vars['view_mode'] == 'menu_item') {
    $vars['theme_hook_suggestions'][] = 'node__menu_item';
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['node']->type . '__menu_item';
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['node']->nid . '__menu_item';
  }
}

function unhcr_menu() {
  $items['node/get/ajax/%'] = array(
    'page callback'     => 'unhcr_ajax_get_ajax',
    'page arguments'    => array(3),
    'type'              => MENU_CALLBACK,
    'access arguments'  => array('access content'),
    'delivery callback' => 'unhcr_ajax_callback'
  );

  return $items;
}

function unhcr_ajax_get_ajax($nid) {
  $node = node_load($nid);

  return node_view($node,'token');
}

function unhcr_ajax_callback($page_callback_result) {
  print drupal_render($page_callback_result);
}
