<?php
/**
 * @file
 * unhcr.module
 */

function unhcr_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['menu_item'] = array(
    'label' => t('Menu item'),
    'custom settings' => TRUE
  );
}

function unhcr_preprocess_node(&$vars) {
  if ($vars['view_mode'] == 'menu_item') {
    $vars['theme_hook_suggestions'][] = 'node__menu_item';
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['node']->type . '__menu_item';
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['node']->nid . '__menu_item';
  }
}
